# Generated by Django 4.2.30 on 2026-08-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplan', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
