# Generated by Django 4.2.30 on 2026-08-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplan', '0003_task_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
