# Generated by Django 4.2.30 on 2026-08-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document')], max_length=50)),
                ('file_visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], max_length=50)),
                ('file', models.FileField(upload_to='resources/')),
            ],
        ),
    ]
